version: "3.3"

services:
  proxy:
    build: .
    image: decentralize/swarm-tcp-proxy
    environment:
      SERVICE_NAME: app
      SERVICE_PORT: 8080
      CONNECTION_TIMEOUT: 5m
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    networks:
      - backend
    deploy:
      mode: global

  app:
    image: decentralize/proxy-responder
    networks:
      - backend

networks:
  backend:
