version: "3.3"

services:
  proxy:
    build: .
    image: decentralize/swarm-tcp-proxy
    environment:
      SERVICES: "app:8080"
      CONNECTION_TIMEOUT: 5m
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - backend
    deploy:
      mode: global

  app:
    image: decentralize/proxy-responder
    networks:
      - backend

networks:
  backend:
